### ISSUE TITLE
Discord link time out.

### ISSUE THREAD

**Issue by nodgear** [ptkdev/ptkdev-logger#18]
- - This is too simple, so i'm ignoring the template.
 
 Discord link in documentation (supposedly  a redirect) times out.
 Link: http://discord.ptkdev.io/

**Comment by ptkdev** [comment]
Sorry,
My vps is on [ovh](https://news.yahoo.com/fire-breaks-ovh-building-strasbourg-074135784.html) and will be restored next days.
