### ISSUE TITLE
error with import ansiRegex from 'ansi-regex';

### ISSUE THREAD

**Issue by Holybasil** [ptkdev/ptkdev-logger#36]
### Versions

- **Logger Version:** v1.7.2
- **Node Version:** v12.16.1
- **Operating System:** Mac 10.15
- **Terminal:** iTerm2

```js
// a.ts in egg
import Logger from '@ptkdev/logger';
const logger = new Logger();

logger.info('lalal');
```

### Screenshots (Optional)

![CleanShot 2021-07-29 at 17 02 40](https://user-images.githubusercontent.com/21138718/127464265-be3e148d-a41b-4cab-bf9d-0f5a6b1fe471.png)

**Comment by ptkdev** [comment]
Fixed in: **v1.8.0**
